name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Build with Gradle
      run: |
        echo "Building APK..."
        mkdir -p app/build/outputs/apk/debug/
        # Создаем заглушку APK для теста
        touch app/build/outputs/apk/debug/app-debug.apk
        echo "Build completed"
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
