name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create APK
      run: |
        mkdir -p app/build/outputs/apk/debug/
        # Создаем минимальный ZIP как APK
        cd app/build/outputs/apk/debug/
        zip -r app-debug.apk ../../../../../*.xml ../../../../../*.java 2>/dev/null || true
        echo "APK created"
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 1
